version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    env_file:
      - .env
    ports:
      - "8080:8080"

    volumes:
      - .:/code
